### PR TITLE
Fix LoPy4 symbol

### PR DESCRIPTION
**Pull request by ayoy**
LoRa chip pins were off by one. I also fixed the direction of other pins, as per commit summary. And I added `.gitignore` because as I'm actively using your library it generates some auxiliary files.

I also have some more fine-grained, pretty accurately measured footprint of the LoPy4, unfinished yet, but so far looking like this:
screen shot 2018-01-19 at 16 01 45

Let me know if you'd be interested in including it in your library and if so, I'll finish it and submit a separate PR.

### CODE REVIEW

**Comment by ep1cman** [comment]
Hi, Thanks for this! in regards to your footprints it would be very interesting to see how they compare, my measurements are based off of the gerber files for the pycom boards.

**Comment by ayoy** [comment]
Oh, I see. Well, I measured the board with a calliper, to be honest :) but as far as pins are concerned, they fit a 2.54mm grid so it's a no-brainer, but (at least for the LoPy with headers) the actual board is wider than what's currently in the library - it expands to the outer pin edges, not their centres. Perhaps it's hair-splitting though :)

**Comment by ep1cman** [comment]
thats a good point actually, I can fix this when I get a chance or if you would like to that would be awesome.

**Comment by ayoy** [comment]
Sure, I'll let you know once I have it sorted out.

**Pull request merged**
